### ISSUE TITLE
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by alinemone** [nWidart/laravel-modules#1727]
Hello, guys!

I've encountered an issue. When I try to install the `nwidart/laravel-modules` v8.2 package on Laravel version 8.83.27, it gives the following error when trying to execute the command "Generating optimized autoload files":

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi


  An option shortcut cannot be empty.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by vivdesign** [comment]
Symfony console in 5.4.35 has change the InputOption constructor $shortcut parameter validation and if false is passed this error appears.
Change the line selected in the screen shot
![image](https://github.com/nWidart/laravel-modules/assets/6173555/cede9393-fa7f-4ab8-ae96-8187f366af5a)

**Comment by dcblogdev** [comment]
done a release for this now.

**Comment by krinkel** [comment]
the issue still exists on Laravel 7 that using "nwidart/laravel-modules": "^7.0",

**Comment by kreemov** [comment]
> yep, that solved it, thanks @vivdesign I'll get a patch release for v8 out.
> 
> @alinemone If you can upgrade Laravel v8 is no longer supported by the Laravel team. https://laravelversions.com/en

appreciate if you can explain how to use this tag/release https://github.com/nWidart/laravel-modules/releases/tag/v8.4.0

**Comment by dcblogdev** [comment]
8.4 is not correct, working on it.

**Comment by azeiee1010** [comment]
When I ran the "composer update" command I got the same issue.

`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi


  An option shortcut cannot be empty.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

Now for all the php artisan commands I am getting "An option shortcut cannot be empty."

How can I fix this issue?

**Comment by RamilYanEh** [comment]
Good Day 

Is there an alternative to fix this issue ?

**Comment by azeiee1010** [comment]
> Good Day
> 
> Is there an alternative to fix this issue ?

Use @vivdesign solution. It worked.

**Comment by alinemone** [comment]
hello 
dose it mean there's a new tag to fix this issue that hasn't been released yet?
how can i resolve this issue during the build process?
