### ISSUE TITLE
autoloading Providers in laravel11x issue on github action composer install

### ISSUE THREAD

**Issue by mauritskorse** [nWidart/laravel-modules#1922]
After upgrading to laravel 11.x I adjusted the composer.json according to the upgrading docs.
When building locally (using sail) everything works fine.
However when pushing to my server through github actions the following fails:
```cmd
RUN composer install --no-dev --ignore-platform-reqs --no-interaction --prefer-dist --no-plugins --optimize-autoloader
```
It returns the following error:
```
In ProviderRepository.php line 206:                                                              
Class "Modules\Admin\Providers\AdminServiceProvider" not found  
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

Reverting the following change back fixes this issue:
```json
     "autoload": {
         "psr-4": {
             "App\\": "app/",
-            "Modules\\": "modules/", <-- delete this
             "Database\\Factories\\": "database/factories/",
             "Database\\Seeders\\": "database/seeders/"
         }
```

I have tried a different approach on the composer install, but no success so far. Any other suggestions?

**Comment by alissn** [comment]
Hi,
@mauritskorse 

To load the module with the package `wikimedia/composer-merge-plugin`, don't use the `--no-plugins` option in your install command. Remove that option and try running the command again.

**Comment by soulevilx** [comment]
Sadly I have exactly same issue
- Create new Laravel 11
- Install Modules
- Publish provider . No config changing
- Create Module : Core
- Create second module : Client

 Class "Modules\Core\Providers\CoreServiceProvider" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206

**Comment by soulevilx** [comment]
> After upgrading to laravel 11.x I adjusted the composer.json according to the upgrading docs. When building locally (using sail) everything works fine. However when pushing to my server through github actions the following fails:
> 
> ```batchfile
> RUN composer install --no-dev --ignore-platform-reqs --no-interaction --prefer-dist --no-plugins --optimize-autoloader
> ```
> 
> It returns the following error:
> 
> ```
> In ProviderRepository.php line 206:                                                              
> Class "Modules\Admin\Providers\AdminServiceProvider" not found  
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> ```
> 
> Reverting the following change back fixes this issue:
> 
> ```json
>      "autoload": {
>          "psr-4": {
>              "App\\": "app/",
> -            "Modules\\": "modules/", <-- delete this
>              "Database\\Factories\\": "database/factories/",
>              "Database\\Seeders\\": "database/seeders/"
>          }
> ```
> 
> I have tried a different approach on the composer install, but no success so far. Any other suggestions?

I have fixed w/ below extra
`    "extra": {
        "laravel": {
            "dont-discover": []
        },
        "merge-plugin": {
            "include": [
                "composer.local.json",
                "Modules/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "ignore-duplicates": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-replace": true,
            "merge-scripts": false
        }
    },`

**Comment by alissn** [comment]
Hi @soulevilx,

Based on the source code, after creating a new module, the command `composer dump-autoload` is automatically run. However, if you still encounter issues, please try running `composer dump-autoload` manually to ensure everything is loaded correctly.

If you continue to experience problems, please let me know.

Reference: https://github.com/nWidart/laravel-modules/blob/b51e39ce8283b118349bcc8510205020a8539080/src/Commands/Make/ModuleMakeCommand.php#L56-L61

**Comment by adelkedjour** [comment]
I don't have  `"Modules\\": "modules/"` in my `composer.json` but still having the same issue.

**Comment by mahdimirhendi** [comment]
The issue occurs after creating a module in Laravel 11, where we encounter the following error:
Class "Modules\Blog\Providers\BlogServiceProvider" not found.

This error is accurate because we don't have BlogServiceProvider in the Blog/Providers directory; instead, it's located in Blog/App/Provider. However, the system is trying to access it from the wrong location. How can we resolve this?

@alissn

**Comment by ProsspaTUN** [comment]
it's bugs, I can't work with modules (

**Comment by ProsspaTUN** [comment]
The solution for me, I don't know if it's right.

But you need to remove the provider registry in **modules.json**

And move provider it to **bootstrap/providers.php**

You need to explicitly specify the provider and correct the namespace

![Снимок экрана 2024-09-04 в 13 01 55](https://github.com/user-attachments/assets/cc7ef16b-9cb4-4ed7-a897-0847fb5b7d65)

**Comment by alissn** [comment]
Hi @ProsspaTUN,

Could you create a new demo project that reproduces this issue and push it to GitHub? This will help me better understand and diagnose the problem.

Thanks!

**Comment by AratKruglik** [comment]
The same issue for me. Any solutions here doesn't help me (

**Comment by ProsspaTUN** [comment]
[alissn](https://github.com/alissn)
![Снимок экрана 2024-09-11 в 10 18 48](https://github.com/user-attachments/assets/172d09e7-19d0-4b03-8624-c8d05a521b2c)
The modules must contain this file, that solution for me

**Comment by ProsspaTUN** [comment]
compose.json must contain for next code

Example:

{
    "name": "nwidart/profile",
    "description": "",
    "authors": [
        {
            "name": "Nicolas Widart",
            "email": "n.widart@gmail.com"
        }
    ],
    "extra": {
        "laravel": {
            "providers": [],
            "aliases": {

            }
        }
    },
    "autoload": {
        "psr-4": {
            "Modules\\Profile\\": "app/",
            "Modules\\Profile\\Database\\Factories\\": "database/factories/",
            "Modules\\Profile\\Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Modules\\Profile\\Tests\\": "tests/"
        }
    }
}

**Comment by edeoliv** [comment]
> > After upgrading to laravel 11.x I adjusted the composer.json according to the upgrading docs. When building locally (using sail) everything works fine. However when pushing to my server through github actions the following fails:
> > ```batchfile
> > RUN composer install --no-dev --ignore-platform-reqs --no-interaction --prefer-dist --no-plugins --optimize-autoloader
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It returns the following error:
> > ```
> > In ProviderRepository.php line 206:                                                              
> > Class "Modules\Admin\Providers\AdminServiceProvider" not found  
> > Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reverting the following change back fixes this issue:
> > ```json
> >      "autoload": {
> >          "psr-4": {
> >              "App\\": "app/",
> > -            "Modules\\": "modules/", <-- delete this
> >              "Database\\Factories\\": "database/factories/",
> >              "Database\\Seeders\\": "database/seeders/"
> >          }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have tried a different approach on the composer install, but no success so far. Any other suggestions?
> 
> I have fixed w/ below extra ` "extra": { "laravel": { "dont-discover": [] }, "merge-plugin": { "include": [ "composer.local.json", "Modules/*/composer.json" ], "recurse": true, "replace": false, "ignore-duplicates": false, "merge-dev": true, "merge-extra": false, "merge-extra-deep": false, "merge-replace": true, "merge-scripts": false } },`

I corrected the error using this extra as well, thanks

**Comment by ben-steve-sc** [comment]
This issue is marked as closed but I encountered this issue today (`v11.1.7`). 

Seems to be an issue with PSR auto-loading. Resolved it by moving the folders in `{module}/app` (`Http` and `Providers`) into the modules root directory and changing the psr4 autoload to the root directory in the module's composer.json.

`Modules/{module}/composer.json`:
```json
    "autoload": {
        "psr-4": {
            "Modules\\Module\\": "",
            "Modules\\Module\\Database\\Factories\\": "database/factories/",
            "Modules\\Module\\Database\\Seeders\\": "database/seeders/"
        }
    },
```

The following warning will still be encountered on `composer dump-autoload` though:

```sh
Class Modules\Module\Database\Seeders\ModuleDatabaseSeeder located in [...]/Modules\Module\database\seeders\ModuleDatabaseSeeder.php does not comply with psr-4 autoloading standard. Skipping.                                                                                                                   
```

**Comment by freescout-help** [comment]
Maybe this would help someone: https://github.com/nWidart/laravel-modules/issues/2008#issuecomment-2603720362
