### ISSUE TITLE
Artisan clear-compiled should also clear [module_name]_module.php files

### ISSUE THREAD

**Issue by Levivb** [nWidart/laravel-modules#494]
Hey,

Related to this issue: https://github.com/nWidart/laravel-modules/issues/495

Not a single command to flush any of the caches (`redis flushall`, `artisan cache:clear`, `artisan view:clear`, `artisan clear-compiled`), does actually flush the `[module_name]_module.php` in `bootstrap/cache` directory (`laravel-modules/src/Laravel/Module.php:18`).

When upgrading from `laravel-modules` `v1.30` to `v2.7` the cached service files are generated once and then never flushed. So after setting the property `defer` in a Module provided ServiceProvider to `false`, the change is ignored forever. (or until you manually remove `bootstrap/cache/*.php`).

It would be nice to remove module generated cache files with the `art clear-compiled` command.

Can you look into that?
Thanks in advanced.

Regards,
Levi

**Comment by nWidart** [comment]
I'll close this as it seems to have been fixed with the related issue. 👍

**Comment by tanero** [comment]
Hi, issue is still exists and solution is not clear. Is there a way to clear modulename_module.php files from bootstrap/cache folder from artisan command ?

**Comment by ctf0** [comment]
atm we have 2 options

- listen to the `optimize:clear` cmnd and clear the files using glob ex.
```php
Event::listen('Illuminate\Console\Events\CommandStarting', function ($event) { // or CommandFinished
    if ($event->command == 'optimize:clear') {
        File::delete(File::glob('bootstrap/cache/*_module.php'));
    }
});
```
- create a cmnd that remove the files and run it when needed
